export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const RETRIEVE_PATIENTS = "RETRIEVE_PATIENTS";
export const RETRIEVE_PATIENT_READINGS = "RETRIEVE_PATIENT_READINGS"
export const RETRIEVE_PATIENT_MEALS = "RETRIEVE_PATIENT_MEALS"
export const RETRIEVE_PATIENT_INSULINS = "RETRIEVE_PATIENT_INSULINS"
export const RETRIEVE_PATIENT_PARAMETERS = "RETRIEVE_PATIENT_PARAMETERS"